version: '2'

services:
  nginx:
    image: docker.io/bitnami/nginx:1.21
    ports:
      - '80:8080'
    volumes:
      - ./my_server_block.conf:/app/nginx/bitnami/nginx/conf/server_blocks/my_server_block.conf
      - ./:/app
