---
- name: nginx install
  apt:
    name: nginx
    state: '{{ item }}'
    update_cache: yes
  with_items:
    - absent
    - present

- name: installing tools
  apt:
    name: '{{ php_modules }}'
    state: present
    update_cache: yes

- name: installing tools
  apt: >
    package={{ item }}
    state=present
    update_cache=yes
  with_items:
    - git
    - mysql-client
    - unzip
    - mc
    - net-tools
    - htop