resource "local_file" "prod" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [all:vars]
    ansible_user = centos
    clickhouse01_ip = ${yandex_compute_instance.node01.network_interface.0.nat_ip_address}

    [nodes:children]
    clickhouse01
    vector01
    lighthouse01

    [clickhouse:children]
    clickhouse01

    [vector:children]
    vector01

    [lighthouse:children]
    lighthouse01

    [clickhouse01]
    clickhouse01.ru-central1.internal ansible_host=${yandex_compute_instance.node01.network_interface.0.nat_ip_address}

    [vector01]
    vector01.ru-central1.internal ansible_host=${yandex_compute_instance.node02.network_interface.0.nat_ip_address}

    [lighthouse01]
    lighthouse01.ru-central1.internal ansible_host=${yandex_compute_instance.node03.network_interface.0.nat_ip_address}

    DOC
  filename = "../inventory/prod.yml"

  depends_on = [
    yandex_compute_instance.node01,
    yandex_compute_instance.node02,
    yandex_compute_instance.node03
  ]
}
