resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [all:vars]
    ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${yandex_compute_instance.nginx.network_interface.0.nat_ip_address}"'
    domain = "antonh2o.ru"
    localdomain = "ru-central1.internal"
    email = "antonh2o@gmail.com"
    token = "wordpress"
    alertmanager_auth_username ="username"
    alertmanager_auth_identity = "identity"
    alertmanager_auth_password = "password"
    smarthost = "gmail.google.com"
    gitlab_domain = "gitlab.antonh2o.ru"
    gitlab_ip = ${var.gitlab_ip}
    app_ip = ${var.app_ip}
    monitoring_ip = ${var.monitoring_ip}
    runner_ip = ${var.runner_ip}
    nginx_ip=${var.nginx_ip}
    db01=${yandex_compute_instance.db01.network_interface.0.ip_address}
    db02=${yandex_compute_instance.db02.network_interface.0.ip_address}

    [app]
    app.ru-central1.internal ansible_host=${yandex_compute_instance.app.network_interface.0.ip_address}

    [nginx]
    antonh2o.ru ansible_host=${yandex_compute_instance.nginx.network_interface.0.nat_ip_address}

    [mysql:children]
    db01
    db02

    [db01]
    db01.ru-central1.internal ansible_host=${yandex_compute_instance.db01.network_interface.0.ip_address}
    [db02]
    db02.ru-central1.internal ansible_host=${yandex_compute_instance.db02.network_interface.0.ip_address}

    [gitlab]
    gitlab.ru-central1.internal ansible_host=${yandex_compute_instance.gitlab.network_interface.0.ip_address}

    [runner]
    runner.ru-central1.internal ansible_host=${yandex_compute_instance.runner.network_interface.0.ip_address}


    [monitoring]
    monitoring.ru-central1.internal ansible_host=${yandex_compute_instance.monitoring.network_interface.0.ip_address}

    DOC
  filename = "../ansible/inventory.yml"

  depends_on = [
    yandex_compute_instance.app,
    yandex_compute_instance.nginx,
    yandex_compute_instance.gitlab,
    yandex_compute_instance.runner,
    yandex_compute_instance.monitoring,
    yandex_compute_instance.db01,
    yandex_compute_instance.db02
  ]
}

resource "local_file" "output" {
  content = <<-DOC
    vm_app_private=${yandex_compute_instance.app.network_interface.0.ip_address}
    vm_db01_private=${yandex_compute_instance.db01.network_interface.0.ip_address}
    vm_db02_private=${yandex_compute_instance.db02.network_interface.0.ip_address}
    vm_gitlab_private=${yandex_compute_instance.gitlab.network_interface.0.ip_address}
    vm_monitoring_private=${yandex_compute_instance.monitoring.network_interface.0.ip_address}
    vm_proxy_private=${yandex_compute_instance.nginx.network_interface.0.ip_address}
    vm_runner_private=${yandex_compute_instance.runner.network_interface.0.ip_address}
    DOC
  filename = "./output.json"

  depends_on = [
    yandex_compute_instance.app,
    yandex_compute_instance.nginx,
    yandex_compute_instance.gitlab,
    yandex_compute_instance.runner,
    yandex_compute_instance.monitoring,
    yandex_compute_instance.db01,
    yandex_compute_instance.db02
  ]
}
