#node_exporter
node_exporter_version: 1.1.2
node_exporter_bin_path: /usr/local/bin/node_exporter
node_exporter_host: "localhost"
node_exporter_port: 9100
node_exporter_options: ''
node_user: "node_exporter"
node_group: "node_exporter"

