---
  - name: Updating remote system
    apt:
      update_cache: yes

  - name: Adding gpg key
    shell: curl https://packages.grafana.com/gpg.key | sudo apt-key add -

  - name: Adding repository 
    apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      state: present

  - name: Installing grafana
    apt:
      name: grafana
      state: present
      update_cache: yes

  - name: Enabling and starting grafana service
    service:
      name: grafana-server
      enabled: yes
      state: started

  - name: Copy datasource to grafana-server
    copy:
      src: datasources/
      dest: /etc/grafana/provisioning/datasources/

  - name: Copy dashboards to grafana-server
    copy:
      src: dashboards/
      dest: /etc/grafana/provisioning/dashboards/

  - name: change admin password for grafana gui
    shell: "grafana-cli admin reset-admin-password {{ grafana_admin_password }}"
    register: _command_admin
    changed_when: _command_admin.rc !=0

  - name: install grafana-cli plugins install grafana-piechart-panel
    shell: "grafana-cli plugins install grafana-piechart-panel"
    register: _command_admin
    changed_when: _command_admin.rc !=0

  - name: install grafana-cli plugins install singlestat-panel
    shell: "grafana-cli plugins install grafana-singlestat-panel"
    register: _command_admin
    changed_when: _command_admin.rc !=0

  - name: Restarting grafana service
    service:
      name: grafana-server
      enabled: yes
      state: restarted

